substitutions:
  name: bw-shp10
  friendly_name: "BlitzWolf SHP10"

esp8266:
  board: esp8285
  
esphome:
  name: $name
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  
  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: zsebastjan.blitzwolf-shp10
    version: "1.7"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://zsebastjan/esphome-configurations/blitzwolf-shp10.yaml@v1.7

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $name
    password: "12345678"

captive_portal:

# Enable Home Assistant API
api:

ota:

# Example configuration entry
uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 4800
  stop_bits: 1

sensor:
  - platform: bl0940
    uart_id: uart_bus
    voltage:
      name: "${friendly_name} Voltage"
    current:
      name: "${friendly_name} Current"
    power:
      name: "${friendly_name} Power"
      id: socket_power
    energy:
      name: "${friendly_name} Energy"
    internal_temperature:
      name: "${friendly_name} Internal temperature"
    update_interval: 10s
  - platform: total_daily_energy
    name: "${friendly_name} Total Daily Energy"
    power_id: socket_power
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:calendar-today
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
    name: "${friendly_name} Button"

switch:
- platform: gpio
  name: "${friendly_name} Relay"
  pin: GPIO5
  restore_mode: ALWAYS_ON
- platform: gpio
  name: "${friendly_name} LED Blue"
  pin: GPIO4
  inverted: True
  restore_mode: ALWAYS_OFF
