# These substitutions allow the end user to override certain values
substitutions:
  name: "d1mini"
  
esp8266:
  board: d1_mini

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  
  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: zsebastjan.d1mini
    version: "1.0"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://zsebastjan/esphome-configurations/d1mini.yaml@v1.2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1Mini Fallback Hotspot"
    password: "12345678"

captive_portal:
