substitutions:
  devicename: sonoff
  friendly_devicename: "Sonoff Basic"
#  ap_password: !secret ap_password
#  wifi_SSID: !secret wifi_SSID
#  wifi_password: !secret wifi_password
  esphome_password: !secret esphome_password
#  use_address: sonoff-e4b5c6.local

esphome:
  name: $devicename
  name_add_mac_suffix: true
  platform: ESP8266
  board: sonoff_basic
  
  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: zsebastjan.sonoff_basic
    version: "1.0"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://zsebastjan/esphome-configurations/sonoff-basic.yaml


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: $esphome_password

wifi:
  use_address: $use_address
  ssid: $wifi_SSID
  password: $wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename
    password: $ap_password

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: ${friendly_devicename} Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: ${friendly_devicename} Relay
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
